version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - src/web/.env
    environment:
      PORT: 8000
    ports:
      - "8000:8000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - src/server/.env
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
