services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - src/web/.env
    ports:
      - "$PORT:$PORT"

  web-local:
    build:
      context: .
      dockerfile: Dockerfile.web.local
    env_file:
      - src/web/.env
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./src/web:/home/node/app
      - ./src/web/node_modules:/home/node/app/node_modules

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - src/server/.env
    ports:
      - "$PORT:$PORT"

  api-local:
    build:
      context: .
      dockerfile: Dockerfile.api.local
    env_file:
      - src/server/.env
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./src/server:/home/node/app
      - ./src/server/node_modules:/home/node/app/node_modules