version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - src/web/.env
    ports:
      - "8000:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - src/server/.env
    ports:
      - "$PORT:$PORT"
