FROM node:19.3.0 as base

WORKDIR /home/node/app
COPY src/web/package.json ./
RUN npm install

FROM base as pre-build
COPY src/web/src ./src
COPY src/web/public ./public

FROM pre-build as build
ARG API_ENDPOINT
ENV API_ENDPOINT=${API_ENDPOINT}
ARG GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
RUN echo > .env
RUN echo API_ENDPOINT=\"${API_ENDPOINT}\" >> .env
RUN echo GENERATE_SOURCEMAP=\"${GENERATE_SOURCEMAP}\" >> .env
RUN npm run build

FROM nginx:alpine as web
COPY src/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/app/build /etc/nginx/html