apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE
  template:
    metadata:
      labels:
        app: $IMAGE
    spec:
      containers:
        - name: $IMAGE
          image: $REGISTRY/$IMAGE
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $IMAGE
  namespace: $K8S_NAMESPACE
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: $IMAGE